# Generated by Django 3.1.1 on 2020-09-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='first_len',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='second_len',
            field=models.CharField(max_length=200),
        ),
    ]
