# Generated by Django 3.0.3 on 2020-11-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered',
            field=models.CharField(default='Ordered', max_length=50),
        ),
    ]
