# Generated by Django 3.0 on 2020-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_len',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='second_len',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admin_detail',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='search',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
