# Generated by Django 3.1.1 on 2020-11-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201115_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
