# Generated by Django 3.0.3 on 2020-11-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201103_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=200)),
                ('cid', models.CharField(max_length=50)),
            ],
        ),
    ]
