# Generated by Django 3.0 on 2020-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200816_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='first_len',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='second_len',
            field=models.CharField(max_length=30),
        ),
    ]
