# Generated by Django 3.0.3 on 2020-11-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_paymentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer',
            field=models.ForeignKey(blank=True, default=100, on_delete=django.db.models.deletion.CASCADE, to='shop.Customer'),
            preserve_default=False,
        ),
    ]
