# Generated by Django 3.0.3 on 2020-08-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200817_0353'),
        ('shop', '0005_auto_20200817_0930'),
    ]

    operations = [
    ]
